---
kind: pipeline
name: lint
clone:
  git:
    image: plugins/git
    tags: true

steps:
- name: lint
  image: renaudhager/go-ci:0.1.3
  commands:
  - make deps
  - make lint

---
kind: pipeline
name: test
clone:
  git:
    image: plugins/git
    tags: true

steps:
- name: test
  image: renaudhager/go-ci:0.1.3
  commands:
  - make deps
  - make test
  - /usr/local/bin/codecov.bash
  environment:
    CODECOV_TOKEN:
      from_secret: CODECOV_TOKEN

---
kind: pipeline
name: build
clone:
  git:
    image: plugins/git
    tags: true

steps:
- name: build
  image: renaudhager/go-ci:0.1.3
  commands:
  - make deps
  - make build

depends_on:
  - lint
  - test

---
kind: pipeline
name: release
clone:
  git:
    image: plugins/git
    tags: true

steps:
- name: create release
  image: renaudhager/go-ci:0.1.3
  commands:
  - make release
  environment:
    GITHUB_USER: "renaudhager"
    GITHUB_TOKEN:
      from_secret: GITHUB_TOKEN

depends_on:
  - lint
  - test
  - build

when:
    branch:
    - master

trigger:
  event:
    - tag
---
kind: signature
hmac: 2b636f762d9b9b2f2f3e6dcc28958619f74461383dcb7ed64671017b26ea703d

...
