---
kind: pipeline
name: build
clone:
  git:
    image: plugins/git
    tags: true

steps:
- name: setup
  image: golang:1.12
  commands:
  - make setup

- name: deps
  image: golang:1.12
  commands:
  - make deps

- name: lint
  image: golang:1.12
  commands:
  - make lint

- name: test
  image: golang:1.12
  commands:
  - make test

- name: build
  image: golang:1.12
  commands:
  - make build
