---
kind: pipeline
name: lint
clone:
  git:
    image: plugins/git
    tags: true

steps:
- name: lint
  image: renaudhager/go-ci:b2cfaef
  commands:
  - make deps
  - make lint

---
kind: pipeline
name: test
clone:
  git:
    image: plugins/git
    tags: true

steps:
- name: test
  image: renaudhager/go-ci:b2cfaef
  commands:
  - make deps
  - make test
  - /usr/local/bin/codecov.bash
  environment:
    CODECOV_TOKEN:
      from_secret: CODECOV_TOKEN

---
kind: pipeline
name: build
clone:
  git:
    image: plugins/git
    tags: true

steps:
- name: build
  image: renaudhager/go-ci:b2cfaef
  commands:
  - make deps
  - make build

depends_on:
  - lint
  - test

---
kind: signature
hmac: cc7f358bfa50620ead1f3b6bb2c8156c93735423822c409b6bb2a72da0552d50

...
