---
kind: pipeline
name: lint
clone:
  git:
    image: plugins/git
    tags: true

steps:
- name: lint
  image: renaudhager/go-ci:4d363b7
  commands:
  - make deps
  - make lint

---
kind: pipeline
name: test
clone:
  git:
    image: plugins/git
    tags: true

steps:
- name: test
  image: renaudhager/go-ci:4d363b7
  commands:
  - make deps
  - make test
  - /usr/local/bin/codecov.bash
  environment:
    CODECOV_TOKEN:
      from_secret: CODECOV_TOKEN

---
kind: pipeline
name: release
clone:
  git:
    image: plugins/git
    tags: true

steps:
- name: build
  image: renaudhager/go-ci:4d363b7
  commands:
  - make deps
  - make build
- name: create release
  image: renaudhager/go-ci:4d363b7
  commands:
  - make release
  environment:
    GITHUB_USER: "renaudhager"
    GITHUB_TOKEN:
      from_secret: GITHUB_TOKEN

depends_on:
  - lint
  - test

when:
    branch:
    - master

trigger:
  event:
    - tag
---
kind: signature
hmac: 06e61db79a5d306c5d2234fe76bbe8a86b7d2753d664d80b57554269018dc9ec

...
