---
kind: pipeline
name: lint
clone:
  git:
    image: plugins/git
    tags: true

steps:
- name: lint
  image: renaudhager/go-ci:latest
  commands:
  - make deps
  - make lint

---
kind: pipeline
name: test
clone:
  git:
    image: plugins/git
    tags: true

steps:
- name: test
  image: renaudhager/go-ci:latest
  commands:
  - make deps
  - make test

---
kind: pipeline
name: build
clone:
  git:
    image: plugins/git
    tags: true

steps:
- name: build
  image: renaudhager/go-ci:latest
  commands:
  - make deps
  - make build

depends_on:
  - lint
  - test

---
kind: signature
hmac: 0b30a65ab246855de68482ae56d1444a293ab6d8c74c35bc9e3d5c4a8dd86112
